### ISSUE TITLE
No get Method Array Access

### ISSUE THREAD

**Issue by NiranjanShah** [mvysny/beverage-buddy-vok#1] opened 2018-02-25 13:27 UTC
Category[categoryId] - > in CategoryList.kt gives error stating [No get Method providing array access]

**Comment by NiranjanShah** [comment] 2018-02-25 13:28
Modifying it to Category.get(categoryId) , at least does not give error while editing

**Comment by mvysny** [comment] 2018-02-25 13:33
Reproduced:

![screenshot from 2018-02-25 15-31-29](https://user-images.githubusercontent.com/254091/36641962-fc660b16-1a40-11e8-902b-60bf7802f377.png)

Looks like a bug in Kotlin plugin for Intellij - it should auto-import the `[]` operator. If you agree, could you please file a bug for the Kotlin plugin in the Jetbrains bug tracker?

Workaround is to place the cursor at the `[` character and press `Alt+Enter` and choose *Import* - that should fix the import and fix the compilation error.

**Comment by NiranjanShah** [comment] 2018-02-25 13:36
For me even auto import is not working.

Will raise the issue, however i believe using Category.get(categoryId) will not give any functional issue?

Please suggest


Regards
Niranjan G Shah

**Comment by NiranjanShah** [comment] 2018-02-25 13:39
Also,

why shall we use Category[categoryId], will it search for Category.id = value or is it the element of a array?


if it is element, then this may give functional issue as the array may be of filtered list.

kindly guide


Regards
Niranjan G Shah

**Comment by mvysny** [comment] 2018-02-25 13:43
>  i believe using Category.get(categoryId) will not give any functional issue?

Yes, `Category[25]` and `Category.get(25)` is completely the same thing. Kotlin compiler emits the very same code for both notations.

> why shall we use Category[categoryId], will it search for Category.id = value or is it the element of a array?

`Category[categoryId]` is just a short-hand for `Category.get(categoryId)`. That means that `vok-orm` will in both cases go and fetch the category with given ID.

It only looks like an access to an array; it's really a `select * from Category where id=:categoryId`. The original intent was that `Category` class is an image for the `category` database table which is a list of categories; hence `Category[id]` would fetch just a single item from the list.

**Comment by mvysny** [comment] 2018-02-25 13:49
It was not my intent to confuse the programmer. Please, if the `Category[25]` notation looks confusing to you, please open a bug report at https://github.com/mvysny/vok-orm and please describe in more detail why you perceive it as confusing.

**Comment by mvysny** [comment] 2018-02-25 16:44
Related issue: https://github.com/mvysny/vok-orm/issues/1

**Comment by mvysny** [comment] 2018-02-25 17:28
Fixed in fcae18981c0ffc0144c22d60c99c12683571f11f

**Closed** 2018-02-25 17:28 UTC
Labels: bug
